trigger:
- none
#- main
resources:
- repo: self

stages:
- stage: IaC_TF
  displayName: Terraform infrastructure
  jobs:
  - job: Init
    displayName: Init
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'AzureRM-sp-Gediminas-Palskis'
        backendAzureRmResourceGroupName: 'Gediminas_Palskis_rg'
        backendAzureRmStorageAccountName: 'gedpalsa1'
        backendAzureRmContainerName: 'tf-state'
        backendAzureRmKey: 'tf/terraform.tfstate'
      displayName: 'Terraform init'


